### ISSUE TITLE
SyntaxError: Unexpected token 'export' 

### ISSUE THREAD

**Issue by abdullahmujahidali** [filipdanic/compact-timezone-list#6]
I am using it in my next JS app and this is the error that I am getting. However, when I check compact-timezone-list index.js it is exporting.

export default [
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)

**Comment by wparad** [comment]
This is solved by #5, but it seams the maintainer is not interested in solving this problem.
